
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 27 22:04:05 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 39;
  public static final int LCBR = 23;
  public static final int LTE = 30;
  public static final int SEMI = 36;
  public static final int CONTINUE = 5;
  public static final int INT = 10;
  public static final int MINUS = 43;
  public static final int STATIC = 15;
  public static final int LT = 28;
  public static final int LP = 22;
  public static final int COMMA = 41;
  public static final int CLASS = 4;
  public static final int RP = 25;
  public static final int MULTIPLY = 38;
  public static final int PLUS = 37;
  public static final int QUOTE = 48;
  public static final int ASSIGN = 40;
  public static final int IF = 9;
  public static final int THIS = 16;
  public static final int ID = 46;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RCBR = 26;
  public static final int LB = 21;
  public static final int LAND = 33;
  public static final int RETURN = 14;
  public static final int EQUAL = 31;
  public static final int TRUE = 17;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int RB = 24;
  public static final int LOR = 35;
  public static final int NULL = 13;
  public static final int NUMBER = 45;
  public static final int MOD = 44;
  public static final int BREAK = 3;
  public static final int VOID = 18;
  public static final int GTE = 29;
  public static final int ELSE = 7;
  public static final int WHILE = 19;
  public static final int NEQUAL = 32;
  public static final int CLASS_ID = 47;
  public static final int EXTENDS = 6;
  public static final int STRING = 20;
  public static final int LNEG = 34;
  public static final int FALSE = 8;
  public static final int GT = 27;
  public static final int LENGTH = 11;
}

